[build]
  command = "npm run build"
  publish = "dist"

[dev]
  command = "npm run dev"
  port = 8888  # or any other port you want to use
  targetPort = 3000  # depending on the port your Nuxt app runs on

[[redirects]]
  from = "/*"
  to = "/200.html"
  status = 200
